version: '3.3'

services:
  mysql_db:
    image: mysql:5.7
    command: --character-set-server=utf8 --max_allowed_packet=104857600
    restart: always
    environment:
      MYSQL_DATABASE: 'mail'
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - '3306:3306'
    volumes:
      - '~/mail_db:/var/lib/mysql'